version: '3.3'

services:
   appphp2020lucas:
     depends_on:
       - dblucas  
     image: lucasbongalhardo/newappphp2020:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       - DB_HOST=dblucas
       - DB_USER=root
       - DB_PASSWORD=bob
       - DB_NAME=univille
   dblucas:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
#     command: --init-file /docker-entrypoint-initdb.d/init.sql
#     volumes:
#         - ./data:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: bob
       MYSQL_DATABASE: univille
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob
     volumes:
        - ./db/:/docker-entrypoint-initdb.d